theme: jekyll-theme-slate
title: Marta Mangiarulo's website
description: Research assistant in the [JDM group](https://www2.le.ac.uk/departments/psychology/research/JDMSP/leicester-judgment-and-decision-making-lab)
at the University of Leicester (UK)
